### ISSUE TITLE
Error 500 when creating new user

### ISSUE THREAD

**Issue by alangrafu** [thekampany/tripproject#1]
I just installed tripproject and when trying to register a user I got a SQL error

```
db-1     | 2024-09-06 16:48:57.764 UTC [35] ERROR:  relation "auth_user" does not exist at character 22
db-1     | 2024-09-06 16:48:57.764 UTC [35] STATEMENT:  SELECT 1 AS "a" FROM "auth_user" WHERE UPPER("auth_user"."username"::text) = UPPER('user') LIMIT 1
db-1     | 2024-09-06 16:48:57.785 UTC [36] ERROR:  relation "auth_user" does not exist at character 280
db-1     | 2024-09-06 16:48:57.785 UTC [36] STATEMENT:  SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE UPPER("auth_user"."username"::text) = UPPER('user') LIMIT 21
```

I just cloned the repo, so I guess the current status is from commit https://github.com/thekampany/tripproject/commit/e8c903b60f882c41b2999f029a48f8a8ebb6673e

**Comment by thekampany** [comment]
Hi, this error occurred when doing a register of a user just after filling all the fields of the register user page? And after the command python manage.py migrate ?

**Comment by alangrafu** [comment]
My bad, I didn't run python manage.py migrate. I will close this issue then, but I wonder if it is possible to run those migration commands during the starting of the container.

**Comment by thekampany** [comment]
You are right. I added it. Thanks.
